// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database.Entities
{
    public partial class tblProductQty
    {
        [Key]
        public Guid ProductQtyId { get; set; }
        public Guid? ProductId { get; set; }
        public int? Stocks { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? SellingPrice { get; set; }
        public Guid? UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
    }
}