// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database.Entities
{
    public partial class tblSale
    {
        [Key]
        public Guid SaleId { get; set; }
        [StringLength(50)]
        public string SaleNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SaleDate { get; set; }
        public Guid? ProductId { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? SaleTotal { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Tax { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? NetTotal { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Balance { get; set; }
        public Guid? CustomerId { get; set; }
        public Guid? UserId { get; set; }
    }
}